---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ewascatalog

<!-- badges: start -->
<!-- badges: end -->

This package allows users to query the EWAS Catalog from R.

## Installation

You can install the package from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("MRCIEU/ewascatalog-r")
```
## Examples

This is a basic example which shows you how to solve a common problem:

```{r example}
library(ewascatalog)
## CpG site query
res <- ewascatalog("cg00029284", "cpg")

## Region query
res <- ewascatalog("6:15000000-25000000", "region")

## Gene
res <- ewascatalog("FTO", "gene")

## Trait
res <- ewascatalog("body mass index", "trait")

## EFO
res <- ewascatalog("EFO_0002950", "efo")

## Study
res <- ewascatalog("27040690", "study")

```
